# Generated by Django 2.2.26 on 2022-06-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_crowd'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowd',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
